def find_best_n(n_max: int, f_count: int, target: int) -> int: ...
def full_distribution(n: int, f_count: int) -> list[float]: ...
def ladder_tiers() -> list[tuple[str, str, str, float]]: ...
def prob_event(n: int, f_count: int, target: int) -> float: ...

__all__ = ["find_best_n", "full_distribution", "ladder_tiers", "prob_event"]
